# configure auto-configured MultipartConfigElement
multipart:
  maxFileSize: 50MB
  maxRequestSize: 50MB
  location: ${java.io.tmpdir}

#logging:
#  level.: DEBUG

com:
  justgifit:
    gif-location: ${java.io.tmpdir}}